type Filters = Record<string, (dhatu: string, muladhatu: string) => boolean>;

export const upadeshaFilters: Filters = {
  षोपदेशः: (dhatu) => /^R/.test(dhatu),
  णोपदेशः: (dhatu) => /^N/.test(dhatu),
};

export const svaraFilters: Filters = {
  उदात्तः: (_, muladhatu) => /\|/.test(muladhatu),
  अनुदात्तः: (_, muladhatu) => /_/.test(muladhatu),
};

export const adiFilters: Filters = {
  अजादिः: (dhatu) => /^[aAiIuUqQeEoO]/.test(dhatu),
  इजादिः: (dhatu) => /^[iIuUqQeEoO]/.test(dhatu),
  झलादिः: (dhatu) => /^[kKgfcCjFtTdDwWxXpPbBSRsh]/.test(dhatu),
  हलादिः: (dhatu) => /^[kKgGfcCjJFtTdDNwWxXnpPbBmyvrlSRsh]/.test(dhatu),
  अकारादिः: (dhatu) => /^a/.test(dhatu),
  आकारादिः: (dhatu) => /^A/.test(dhatu),
  इकारादिः: (dhatu) => /^i/.test(dhatu),
  ईकारादिः: (dhatu) => /^I/.test(dhatu),
  उकारादिः: (dhatu) => /^u/.test(dhatu),
  ऊकारादिः: (dhatu) => /^U/.test(dhatu),
  ऋकारादिः: (dhatu) => /^q/.test(dhatu),
  ॠकारादिः: (dhatu) => /^Q/.test(dhatu),
  एकारादिः: (dhatu) => /^e/.test(dhatu),
  ऐकारादिः: (dhatu) => /^E/.test(dhatu),
  ओकारादिः: (dhatu) => /^o/.test(dhatu),
  औकारादिः: (dhatu) => /^O/.test(dhatu),
  ककारादिः: (dhatu) => /^k/.test(dhatu),
  खकारादिः: (dhatu) => /^K/.test(dhatu),
  गकारादिः: (dhatu) => /^g/.test(dhatu),
  घकारादिः: (dhatu) => /^G/.test(dhatu),
  ङकारादिः: (dhatu) => /^f/.test(dhatu),
  चकारादिः: (dhatu) => /^c/.test(dhatu),
  छकारादिः: (dhatu) => /^C/.test(dhatu),
  जकारादिः: (dhatu) => /^j/.test(dhatu),
  झकारादिः: (dhatu) => /^J/.test(dhatu),
  ञकारादिः: (dhatu) => /^F/.test(dhatu),
  टकारादिः: (dhatu) => /^t/.test(dhatu),
  ठकारादिः: (dhatu) => /^T/.test(dhatu),
  डकारादिः: (dhatu) => /^d/.test(dhatu),
  ढकारादिः: (dhatu) => /^D/.test(dhatu),
  णकारादिः: (dhatu) => /^N/.test(dhatu),
  तकारादिः: (dhatu) => /^w/.test(dhatu),
  थकारादिः: (dhatu) => /^W/.test(dhatu),
  दकारादिः: (dhatu) => /^x/.test(dhatu),
  धकारादिः: (dhatu) => /^X/.test(dhatu),
  नकारादिः: (dhatu) => /^n/.test(dhatu),
  पकारादिः: (dhatu) => /^p/.test(dhatu),
  फकारादिः: (dhatu) => /^P/.test(dhatu),
  बकारादिः: (dhatu) => /^b/.test(dhatu),
  भकारादिः: (dhatu) => /^B/.test(dhatu),
  मकारादिः: (dhatu) => /^m/.test(dhatu),
  यकारादिः: (dhatu) => /^y/.test(dhatu),
  रेफादिः: (dhatu) => /^r/.test(dhatu),
  लकारादिः: (dhatu) => /^l/.test(dhatu),
  वकारादिः: (dhatu) => /^v/.test(dhatu),
  शकारादिः: (dhatu) => /^S/.test(dhatu),
  षकारादिः: (dhatu) => /^R/.test(dhatu),
  सकारादिः: (dhatu) => /^s/.test(dhatu),
  हकारादिः: (dhatu) => /^h/.test(dhatu),
};

export const antaFilters: Filters = {
  अजन्तः: (dhatu) => /[aAiIuUqQeEoO]$/.test(dhatu),
  इजन्तः: (dhatu) => /[iIuUqQeEoO]$/.test(dhatu),
  झलन्तः: (dhatu) => /[kKgfcCjFtTdDwWxXpPbBSRsh]$/.test(dhatu),
  हलन्तः: (dhatu) => /[kKgGfcCjJFtTdDNwWxXnpPbBmyvrlSRsh]$/.test(dhatu),
  अकारान्तः: (dhatu) => /a$/.test(dhatu),
  आकारान्तः: (dhatu) => /A$/.test(dhatu),
  इकारान्तः: (dhatu) => /i$/.test(dhatu),
  ईकारान्तः: (dhatu) => /I$/.test(dhatu),
  उकारान्तः: (dhatu) => /u$/.test(dhatu),
  ऊकारान्तः: (dhatu) => /U$/.test(dhatu),
  ऋकारान्तः: (dhatu) => /q$/.test(dhatu),
  ॠकारान्तः: (dhatu) => /Q$/.test(dhatu),
  एकारान्तः: (dhatu) => /e$/.test(dhatu),
  ऐकारान्तः: (dhatu) => /E$/.test(dhatu),
  ओकारान्तः: (dhatu) => /o$/.test(dhatu),
  औकारान्तः: (dhatu) => /O$/.test(dhatu),
  ककारान्तः: (dhatu) => /k$/.test(dhatu),
  खकारान्तः: (dhatu) => /K$/.test(dhatu),
  गकारान्तः: (dhatu) => /g$/.test(dhatu),
  घकारान्तः: (dhatu) => /G$/.test(dhatu),
  ङकारान्तः: (dhatu) => /f$/.test(dhatu),
  चकारान्तः: (dhatu) => /c$/.test(dhatu),
  छकारान्तः: (dhatu) => /C$/.test(dhatu),
  जकारान्तः: (dhatu) => /j$/.test(dhatu),
  झकारान्तः: (dhatu) => /J$/.test(dhatu),
  ञकारान्तः: (dhatu) => /F$/.test(dhatu),
  टकारान्तः: (dhatu) => /t$/.test(dhatu),
  ठकारान्तः: (dhatu) => /T$/.test(dhatu),
  डकारान्तः: (dhatu) => /d$/.test(dhatu),
  ढकारान्तः: (dhatu) => /D$/.test(dhatu),
  णकारान्तः: (dhatu) => /N$/.test(dhatu),
  तकारान्तः: (dhatu) => /w$/.test(dhatu),
  थकारान्तः: (dhatu) => /W$/.test(dhatu),
  दकारान्तः: (dhatu) => /x$/.test(dhatu),
  धकारान्तः: (dhatu) => /X$/.test(dhatu),
  नकारान्तः: (dhatu) => /n$/.test(dhatu),
  पकारान्तः: (dhatu) => /p$/.test(dhatu),
  फकारान्तः: (dhatu) => /P$/.test(dhatu),
  बकारान्तः: (dhatu) => /b$/.test(dhatu),
  भकारान्तः: (dhatu) => /B$/.test(dhatu),
  मकारान्तः: (dhatu) => /m$/.test(dhatu),
  यकारान्तः: (dhatu) => /y$/.test(dhatu),
  रेफान्तः: (dhatu) => /r$/.test(dhatu),
  लकारान्तः: (dhatu) => /l$/.test(dhatu),
  वकारान्तः: (dhatu) => /v$/.test(dhatu),
  शकारान्तः: (dhatu) => /S$/.test(dhatu),
  षकारान्तः: (dhatu) => /R$/.test(dhatu),
  सकारान्तः: (dhatu) => /s$/.test(dhatu),
  हकारान्तः: (dhatu) => /h$/.test(dhatu),
};

export const upadhaFilters: Filters = {
  अकारोपधः: (dhatu) => /a.$/.test(dhatu),
  आकारोपधः: (dhatu) => /A.$/.test(dhatu),
  इकारोपधः: (dhatu) => /i.$/.test(dhatu),
  ईकारोपधः: (dhatu) => /I.$/.test(dhatu),
  उकारोपधः: (dhatu) => /u.$/.test(dhatu),
  ऊकारोपधः: (dhatu) => /U.$/.test(dhatu),
  ऋकारोपधः: (dhatu) => /q.$/.test(dhatu),
  ॠकारोपधः: (dhatu) => /Q.$/.test(dhatu),
  एकारोपधः: (dhatu) => /e.$/.test(dhatu),
  ऐकारोपधः: (dhatu) => /E.$/.test(dhatu),
  ओकारोपधः: (dhatu) => /o.$/.test(dhatu),
  औकारोपधः: (dhatu) => /O.$/.test(dhatu),
  ककारोपधः: (dhatu) => /k.$/.test(dhatu),
  खकारोपधः: (dhatu) => /K.$/.test(dhatu),
  गकारोपधः: (dhatu) => /g.$/.test(dhatu),
  घकारोपधः: (dhatu) => /G.$/.test(dhatu),
  ङकारोपधः: (dhatu) => /f.$/.test(dhatu),
  चकारोपधः: (dhatu) => /c.$/.test(dhatu),
  छकारोपधः: (dhatu) => /C.$/.test(dhatu),
  जकारोपधः: (dhatu) => /j.$/.test(dhatu),
  झकारोपधः: (dhatu) => /J.$/.test(dhatu),
  ञकारोपधः: (dhatu) => /F.$/.test(dhatu),
  टकारोपधः: (dhatu) => /t.$/.test(dhatu),
  ठकारोपधः: (dhatu) => /T.$/.test(dhatu),
  डकारोपधः: (dhatu) => /d.$/.test(dhatu),
  ढकारोपधः: (dhatu) => /D.$/.test(dhatu),
  णकारोपधः: (dhatu) => /N.$/.test(dhatu),
  तकारोपधः: (dhatu) => /w.$/.test(dhatu),
  थकारोपधः: (dhatu) => /W.$/.test(dhatu),
  दकारोपधः: (dhatu) => /x.$/.test(dhatu),
  धकारोपधः: (dhatu) => /X.$/.test(dhatu),
  नकारोपधः: (dhatu) => /n.$/.test(dhatu),
  पकारोपधः: (dhatu) => /p.$/.test(dhatu),
  फकारोपधः: (dhatu) => /P.$/.test(dhatu),
  बकारोपधः: (dhatu) => /b.$/.test(dhatu),
  भकारोपधः: (dhatu) => /B.$/.test(dhatu),
  मकारोपधः: (dhatu) => /m.$/.test(dhatu),
  यकारोपधः: (dhatu) => /y.$/.test(dhatu),
  रेफोपधः: (dhatu) => /r.$/.test(dhatu),
  लकारोपधः: (dhatu) => /l.$/.test(dhatu),
  वकारोपधः: (dhatu) => /v.$/.test(dhatu),
  शकारोपधः: (dhatu) => /S.$/.test(dhatu),
  षकारोपधः: (dhatu) => /R.$/.test(dhatu),
  सकारोपधः: (dhatu) => /s.$/.test(dhatu),
  हकारोपधः: (dhatu) => /h.$/.test(dhatu),
};

export const featureFilters: Filters = {
  ...upadeshaFilters,
  ...svaraFilters,
  ...adiFilters,
  ...antaFilters,
  ...upadhaFilters,
};
